openapi: 3.0.0
info:
  title: Task Planner API
  description: API для планирования задач и событий
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Локальный сервер

tags:
  - name: Users
    description: Управление пользователями
  - name: Tasks
    description: Управление задачами
  - name: Notifications
    description: Уведомления и напоминания

paths:
  /users/register:
    post:
      tags:
        - Users
      summary: Регистрация нового пользователя
      requestBody:
        description: Данные для регистрации
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: "password123"
                fullName:
                  type: string
                  example: John Doe
      responses:
        '201':
          description: Успешная регистрация
        '400':
          description: Неверные данные

  /users/login:
    post:
      tags:
        - Users
      summary: Вход в систему
      requestBody:
        description: Данные для авторизации
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Успешный вход
        '401':
          description: Неверные данные авторизации

  /profile:
    post:
      tags:
        - Users
      summary: Обновление профиля пользователя
      description: Обновляет информацию профиля пользователя.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "student123"
                email:
                  type: string
                  example: "student@example.com"
      responses:
        200:
          description: Профиль успешно обновлен
        400:
          description: Неверные данные запроса

  /getTasks:
    get:
      tags:
        - Tasks
      summary: Получение списка задач пользователя
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            example: 5a498320-15de-48b2-b94c-2f5c3a475474
      responses:
        '200':
          description: Список задач
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uid:
                      type: string
                      example: 68345748-84f3-42bc-999b-1ec52581a36b
                    title:
                      type: string
                      example: "Закончить лабораторную работу"
                    description:
                      type: string
                      example: "Сделать лабораторную по физике"
                    dueDate:
                      type: string
                      format: date-time
                      example: "2024-09-12T10:00:00Z"
                    priority:
                      type: integer
                      example: 1
                    status:
                      type: string
                      example: "in progress"
        '401':
          description: Пользователь не авторизован

  /getCurTasks:
    get:
      tags:
        - Tasks
      summary: Получение конкретной задачи
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            example: f4855910-75a7-4477-aea0-7a6d6f95e26c
      responses:
        '200':
          description: Задача получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                    example: 8a994792-ae0b-4e8b-9de3-3e82782e171f
                  title:
                    type: string
                    example: "Закончить лабораторную работу"
                  description:
                    type: string
                    example: "Сделать лабораторную по физике"
                  dueDate:
                    type: string
                    format: date-time
                    example: "2024-09-12T10:00:00Z"
                  priority:
                    type: string
                    enum: ["низкий", "средний", "высокий"]
                    example: "высокий"
                  status:
                    type: string
                    example: "in progress"
        '404':
          description: Задача не найдена

  /tasks:
    post:
      tags:
        - Tasks
      summary: Создание новой задачи
      requestBody:
        description: Данные новой задачи
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Закончить лабораторную работу"
                description:
                  type: string
                  example: "Сделать лабораторную по физике"
                dueDate:
                  type: string
                  format: date-time
                  example: "2024-09-12T10:00:00Z"
                priority:
                  type: string
                  enum: ["низкий", "средний", "высокий"]
                  example: "высокий"
                categoryId:
                  type: integer
                  example: 2
      responses:
        '201':
          description: Задача создана

  /updateTasks:
    put:
      tags:
        - Tasks
      summary: Обновление задачи
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: Данные обновленной задачи
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Закончить лабораторную работу"
                description:
                  type: string
                  example: "Сделать лабораторную по физике"
                dueDate:
                  type: string
                  format: date-time
                  example: "2024-09-12T10:00:00Z"
                priority:
                  type: string
                  enum: ["низкий", "средний", "высокий"]
                  example: "высокий"
                status:
                  type: string
                  example: "in progress"
      responses:
        '200':
          description: Задача обновлена
        '404':
          description: Задача не найдена

  /delTasks:
    delete:
      tags:
        - Tasks
      summary: Удаление задачи
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Задача удалена
        '404':
          description: Задача не найдена

  /notifications:
    post:
      tags:
        - Notifications
      summary: Создание напоминания
      description: Создает напоминание для задачи.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: string
                  example: "64f893b6a726b300f437bb6c"
                notificationTime:
                  type: string
                  format: date-time
                  example: "2024-09-19T09:00:00Z"
      responses:
        201:
          description: Напоминание успешно создано
        400:
          description: Неверные данные запроса


  /updateNotifications:
    post:
      tags:
        - Notifications
      summary: Настройка уведомлений для задачи
      requestBody:
        description: Уведомление для задачи
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskUid:
                  type: string
                  example: f4855910-75a7-4477-aea0-7a6d6f95e26c
                remindAt:
                  type: string
                  format: date-time
                  example: "2024-09-11T09:00:00Z"
                method:
                  type: string
                  example: "email"
      responses:
        '201':
          description: Уведомление настроено
        '400':
          description: Ошибка в данных

components:
  schemas:
    Task:
      type: object
      properties:
        uid:
          type: string
          example: f4855910-75a7-4477-aea0-7a6d6f95e26c
        title:
          type: string
          example: "Подготовка к экзамену"
        description:
          type: string
          example: "Необходимо выучить главы 1-5 по математике"
        dueDate:
          type: string
          format: date-time
          example: "2024-09-20T12:00:00Z"
        priority:
          type: string
          example: высокий
        status:
          type: string
          example: "В процессе"
        categoryId:
          type: integer
          example: 2
        userId:
          type: integer
          example: 1

    User:
      type: object
      properties:
        uid:
          type: string
          example: f4855910-75a7-4477-aea0-7a6d6f95e26c
        email:
          type: string
          example: "student@example.com"
        fullName:
          type: string
          example: "Иван Иванов"
        theme:
          type: string
          example: "dark"
